config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/home' , to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
  resources :events, only: [:new, :create, :show, :index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	scope :past, -> {where("date < ?", Time.now)}
	scope :upcoming, -> {where("date > ?", Time.now)}
	#has_many :ideas
	#what are users? people that have reserved or people that have been invited?
	#has_many :users, through: :ideas
	#belongs_to :creator, :class_name => "User"
	#has_many :invitations, :foreign_key => :invite 
	#has_many :invitees, :through => :invitations, :source => :create_event
	#belongs_to :creator, :class_name => "User"

	has_many :invites, :foreign_key => :authored_event_id
	has_many :attendees, :through => :invites, :source => :event_author
	belongs_to :creator, :class_name => "User"

	#def self.past
	#	where("date < ?", Time.now)
	#end

	#def self.upcoming
	#	where("date > ?", Time.now)
	#end
end

app/models/invite.rb
class Invite < ApplicationRecord
	#name of the association by default tells Rails 
	#that the Invites table has an event_author_id column and to search the event_author table
	#however, the name of the column does not correspond to the correct class.
	#there is no event_author table, so tell rails which table to search
	belongs_to :event_author, :class_name => "User"
	belongs_to :authored_event, :class_name=> "Event"
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
    validates(:password, presence:true, allow_nil: true)
    validates(:name, presence:true)
    validates(:email, presence:true)

    #has_many :ideas
    #has_many :events, through: :ideas
   #  has_many :events, :foreign_key => "creator_id"
    #has_many :creators, :class_name => "Event", :foreign_key => "creator_id"
    #has_many :events, foreign_key =>"creator_id"
    #the above line does not work so we have to change up some names
    #let's get rid of ideas and replace it with invitation

    #THis below works
    #we have access to invitations table and will populate create_event_id with our ID
    #has_many :invitations, :foreign_key => :create_event_id
    #has_many :invites, :through => :invitations
    #has_many :created_events, :foreign_key => :creator_id, :class_name => "Event"
    
    #events we created
    has_many :invites, :foreign_key => :event_author_id
    #has_many :authored_events, :through => :invites
    has_many :attending_events, :through => :invites, :source => :authored_event
    #association name is by default the 
    #name of the table to look up
    #foreign_key is the name_id
    #build-> preopulates foreign key
    #otherwise just searches for its id in the foreign_key column
    has_many :events, :foreign_key => :creator_id

    #returns upcoming events
    def upcoming_events
        attending_events.where("date > ?", Time.now)
    end

    #returns previous events
    def previous_events
        attending_events.where("date < ?", Time.now)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def logged_in?
  	session[:user_id]
  end

  def current_user
  	current_user = User.find_by(id: session[:user_id])
  end

  def logout
  	session[:user_id] = nil
  end

  helper_method :logged_in?, :current_user, :logout
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  
  def new
  end
  
  def index
  	@events = Event.all.collect
  end

  def create
      @event = current_user.events.build(event_params)
      if @event.save
        flash.now[:success] = "Successfully created new event."
        redirect_to @event
      else
        flash.now[:error] = @event.errors.full_messages
        render 'events/new'
      end
  end

  def show
  	@event = Event.find_by(id: params[:id])
  end
    
  private 

  def event_params
    params.require(:event).permit(:name, :place, :date)
  end

  def logged_in_user
    unless logged_in?
      flash.now[:error]= "You are not logged_in."
      redirect_to request.referrer
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(name: params[:session][:name])
  	if @user
  		session[:user_id] = @user.id
  		flash[:success] = "User found."
  		redirect_to @user 
  	else
  		flash.now[:danger] = "User does not exist."
  		render 'sessions/new'
  	end
  end

  def destroy
  	logout
  	flash[:success] = "Logged out."
  	redirect_to request.referrer

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Successfully created new user."
  		redirect_to @user
  	else
  		flash.now[:warning] = @user.errors.full_messages
  		render 'new'
  	end
  end

  def show
      @user = User.find_by(id: params[:id])
      @events = @user.events.collect(&:name)
  end

  private

  def user_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h2>All Events(<%=@events.count%>)</h2>

<%if Event.past.any?%>
	<h3>Previous</h3>
	<%Event.past.each do |e|%>
		<li><%= link_to e.name, event_url(e.id)%></li>
	<%end%>
<% end %>

<% if Event.upcoming.any?%>
	<h3>Upcoming</h3>
	
	<%Event.upcoming.each do |e|%>
	  <p><%=link_to e.name, event_url(e.id)%></p>
     <%end%>
<%end%>

app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

<%=form_for(:event, url: events_path) do |f|%>
	<%=f.label :name%>
	<%=f.text_field :name%><br>

	<%=f.label :place%>
	<%=f.text_field :place%><br>

	<%=f.label :date%>
	<%=f.text_field :date%><br>

	<%=f.submit%>

<%end%>

app/views/events/show.html.erb
<h3>Name</h3>
<p><%=@event.name%></p>
<h3>Place</h3>
<p><%=@event.place%></p>
<h3>Date</h3>
<p><%=@event.date%></p>
<h3>Hosted By</h3>
<p><%=@event.creator.name%></p>

<h4>Attendees(<%=@event.attendees.count%>)</h4>

<%@event.attendees.collect.each do |e|%>
	<li><%=link_to e.name, user_path(e.id)%></li>

<%end%>

app/views/layouts/_footer.html.erb
<footer>

<small>
	<a href="https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations?ref=lc-pb">www.theodinproject.com</a>
</small>

<nav>
	<ul>
		<li><%=link_to 'About', about_path%></li>
		<li><%=link_to 'Help', help_path%></li>
	</ul>
</nav>

</footer>

app/views/layouts/_header.html.erb
<nav class= "navbar navbar-inverse">
    <div class="container">
		<div class="navbar-header">
		   <!--create collapse navbar button here-->
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </button>
       <a href= <%=home_url%> class="navbar-brand">Private Events</a>

		</div>
    
    <div class="collapse navbar-collapse" id="myNavbar">
  		<ul class="nav navbar-nav navbar-right">
  			<li><%=link_to 'Home', home_path%></li>
  		  <li><%=link_to 'All Events', events_path%></li>
        <%if logged_in?%>

          <li class="dropdown">

            <a href= <%=current_user%> class="dropdown-toggle" data-toggle="dropdown" ><%=current_user.name%><span class="caret"></span>
            </a>

            <ul class="dropdown-menu">
              <li><%=link_to 'My profile'%></li>
              <li class="divider"></li>
              <li><%=link_to 'Logout', logout_path, method: :delete%></li>
            </ul>

          </li>
        <%else%>
            <li><%=link_to 'Login', new_session_path%></li>
        <%end%>
  		</ul>
    </div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%=render 'layouts/header'%>

    <div class="container">
      <%flash.each do |type,msg|%>
        <div class= "alert alert-<%=type%>" >
      	   <p><%=type%> : <%=msg%></p>
        </div>
      <%end%>
      <%= yield %>

      <%=render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About</h1>
<p>Allows its users to create events and invite existing users.
Your profile will showcase your past and upcoming events. </p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
	<h1>Welcome</h1>
	<p>This is the homepage for the private events app.</p>

	<a href="<%=new_user_path%>" class="btn btn-primary">Sign up now!</a>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<%= form_for(:user, url: users_path) do |f|%>
			<%= f.label :name%>
			<%= f.text_field :name%><br>

			<%=f.label :email%>
			<%=f.email_field :email%><br>

			<%=f.label :password%>
			<%=f.password_field :password%><br>

			<%=f.label :password_confirmation%>
			<%=f.password_field :password_confirmation%><br>

			<%= f.submit "create user", class: "btn btn-primary"%>
		<%end%>
	</div>
</div>

app/views/users/show.html.erb
Welcome, <%=@user.name%> ! <br>

  <%if @user.events.any?%>
  	<h5>Events created (<%=@user.events.count%>)</h5>
  	    <%@events.each do |e|%>
  		   <p><%=e%><p>
  		<%end%>
  <%end%>

  <%if @user.attending_events.any?%>
  	<h5>Events Attending(<%=@user.attending_events.count%>)</h5>
  	 <%@user.attending_events.collect.each do |e|%>
  	 	<li><%=link_to e.name, event_path(e.id)%></li>
  	 <%end%>
  <%end%>

<h2>Profile page still under construction...</h2>